# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_picture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='upload_date',
            field=models.DateTimeField(default='2000-06-06', verbose_name='date uploaded'),
        ),
    ]
