# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_picture_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded'),
        ),
    ]
